Lint/DuplicateStringLiteral:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'

MyExtension/Example:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '0.1'
